const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#F5A623",
    background: "#FEFDF8",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#F5A623",
    primaryForeground: "#1C1C1E",
    secondary: "#F2F2F2",
    secondaryForeground: "#1C1C1E",
    muted: "#F2F2F2",
    mutedForeground: "#8E8E93",
    accent: "#FFF5E0",
    accentForeground: "#1C1C1E",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5EA",
    input: "#F2F2F7",
  },
  dark: {
    text: "#EBEBF5",
    tint: "#F5A623",
    background: "#1C1C1E",
    foreground: "#EBEBF5",
    card: "#2C2C2E",
    cardForeground: "#EBEBF5",
    primary: "#F5A623",
    primaryForeground: "#1C1C1E",
    secondary: "#3A3A3C",
    secondaryForeground: "#EBEBF5",
    muted: "#3A3A3C",
    mutedForeground: "#8E8E93",
    accent: "#3A3A3C",
    accentForeground: "#EBEBF5",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#3A3A3C",
    input: "#3A3A3C",
  },
  radius: 14,
};

export default colors;
